import { ArrowRight, Blocks, Check, GitBranch, Layers3, LoaderCircle, Play, Plus, Search } from 'lucide-react';
import { useState } from 'react';
import { versionKey, type BlockDefinition, type BlockValue, type PromotionRequest, type Scenario, type StudioCatalog } from '../../shared/blocks';
import { KindIcon } from './Canvas';
import { findDefinition, flattenBlocks, KIND_LABELS, newestDefinitions } from './model';
import { Field, Modal } from './ui';

export function NewScenarioDialog({ mode, current, busy, onClose, onCreate }: { mode: 'new' | 'clone'; current: Scenario; busy: boolean; onClose: () => void; onCreate: (name: string, starter: string) => void }) {
  const [name, setName] = useState(mode === 'clone' ? `${current.name} · variation` : 'My property policy flow');
  const [starter, setStarter] = useState('standard-draft');
  return <Modal title={mode === 'clone' ? 'Create a variation' : 'Create a scenario'} subtitle={mode === 'clone' ? 'An independent copy keeps the same versioned blocks. Change its inputs to test a different case.' : 'Start small with a draft policy, or open an empty canvas.'} onClose={onClose}><form onSubmit={event => { event.preventDefault(); onCreate(name, starter); }}><div className="st-modal-body"><Field label="Scenario name"><input aria-label="Scenario name" value={name} onChange={event => setName(event.target.value)} required autoFocus/></Field>{mode === 'new' && <Field label="Start with"><select aria-label="Scenario starting point" value={starter} onChange={event => setStarter(event.target.value)}><option value="standard-draft">Standard draft · 2 business steps</option><option value="italy-referral">Italy referral · complete business journey</option><option value="empty">Empty canvas</option></select></Field>}<div className="st-new-scenario-intro"><strong>{mode === 'clone' ? 'Changes stay in this variation.' : starter === 'empty' ? 'Build your own sequence.' : 'A working example gives you a starting point.'}</strong><br/>{mode === 'clone' ? 'The original scenario and shared block definitions keep their saved values.' : starter === 'empty' ? 'Add an actor context, then choose business actions from the catalog.' : 'Select a block to change its inputs. Run it to create real records in the local insurance desk.'}</div></div><footer className="st-modal-footer"><button type="button" className="st-button" onClick={onClose}>Cancel</button><button className="st-button st-button-primary" disabled={busy || !name.trim()} data-testid="create-scenario-confirm">{busy ? <LoaderCircle className="st-spin" size={13}/> : <Plus size={13}/>}Create {mode === 'clone' ? 'variation' : 'scenario'}</button></footer></form></Modal>;
}

export function ScenarioDetailsDialog({ scenario, onClose, onSave }: { scenario: Scenario; onClose: () => void; onSave: (values: Pick<Scenario, 'name' | 'description' | 'expectedOutcome' | 'tags'>) => void }) {
  const [name, setName] = useState(scenario.name);
  const [description, setDescription] = useState(scenario.description);
  const [outcome, setOutcome] = useState(scenario.expectedOutcome || '');
  const [tags, setTags] = useState(scenario.tags.join(', '));
  return <Modal title="Scenario details" subtitle="Describe the business case so somebody else can understand the flow." onClose={onClose}><form onSubmit={event => { event.preventDefault(); onSave({ name, description, expectedOutcome: outcome, tags: tags.split(',').map(tag => tag.trim()).filter(Boolean) }); }}><div className="st-modal-body"><Field label="Scenario name"><input aria-label="Scenario name" value={name} onChange={event => setName(event.target.value)} required/></Field><Field label="Description"><textarea aria-label="Scenario description" value={description} onChange={event => setDescription(event.target.value)}/></Field><Field label="Expected outcome"><textarea aria-label="Expected outcome" value={outcome} onChange={event => setOutcome(event.target.value)}/></Field><Field label="Tags" hint="Separate tags with commas."><input aria-label="Scenario tags" value={tags} onChange={event => setTags(event.target.value)}/></Field></div><footer className="st-modal-footer"><button type="button" className="st-button" onClick={onClose}>Cancel</button><button className="st-button st-button-primary" disabled={!name.trim()}><Check size={13}/>Apply details</button></footer></form></Modal>;
}

export function PromotionDialog({ scenario, catalog, busy, error, onClose, onPromote }: { scenario: Scenario; catalog: StudioCatalog; busy: boolean; error?: string; onClose: () => void; onPromote: (request: PromotionRequest) => void }) {
  const [name, setName] = useState(`${scenario.name} workflow`);
  const [description, setDescription] = useState(scenario.description);
  const [selection, setSelection] = useState(scenario.blocks.map(block => block.id));
  const [parameters, setParameters] = useState<PromotionRequest['parameters']>([]);
  const [replace, setReplace] = useState(true);
  const candidates = flattenBlocks(scenario.blocks.filter(block => selection.includes(block.id))).flatMap(block => {
    const def = findDefinition(catalog, block);
    return (def?.inputs || []).filter(input => !input.type.endsWith('Ref') && input.type !== 'Object' && input.type !== 'Role' && input.type !== 'LocationName').map(input => ({ block, def: def!, input }));
  });
  function toggleParameter(instanceId: string, input: string, label: string, type: PromotionRequest['parameters'][number]['type']) {
    const match = parameters.some(param => param.instanceId === instanceId && param.input === input);
    if (match) setParameters(parameters.filter(param => !(param.instanceId === instanceId && param.input === input)));
    else {
      const base = label.replace(/[^a-zA-Z0-9 ]/g, '').split(' ').filter(Boolean).map((word, index) => index ? word[0].toUpperCase() + word.slice(1) : word.toLowerCase()).join('');
      let key = base || input; let suffix = 2;
      while (parameters.some(param => param.key === key)) key = `${base}${suffix++}`;
      setParameters([...parameters, { key, label, instanceId, input, type }]);
    }
  }
  return <Modal title="Save a reusable workflow" subtitle="Give a sequence a business name. Expose the few inputs that should change from one scenario to the next." onClose={onClose} wide><form onSubmit={event => { event.preventDefault(); onPromote({ scenarioId: scenario.id, name, description, instanceIds: selection, parameters: parameters.filter(param => candidates.some(candidate => candidate.block.id === param.instanceId && candidate.input.key === param.input)), replaceSelection: replace }); }}><div className="st-modal-body">{error && <div className="st-alert st-alert-error" style={{ margin: '0 0 17px' }} role="alert">{error}</div>}<div className="st-library-detail-grid"><div><Field label="Reusable block name"><input aria-label="Reusable block name" value={name} onChange={event => setName(event.target.value)} required/></Field><Field label="Description"><textarea aria-label="Reusable block description" value={description} onChange={event => setDescription(event.target.value)}/></Field><div className="st-inspector-section-title" style={{ marginTop: 20 }}>Sequence to include</div><div className="st-checkbox-group">{scenario.blocks.map(block => { const def = findDefinition(catalog, block); return <label key={block.id} className="st-check-field"><input type="checkbox" checked={selection.includes(block.id)} onChange={event => setSelection(scenario.blocks.filter(item => item.id === block.id ? event.target.checked : selection.includes(item.id)).map(item => item.id))}/>{def?.contextType === 'actor' ? `As ${String(block.inputs.role)}` : def?.label || block.definition.id}</label>; })}</div><label className="st-check-field" style={{ marginTop: 15 }}><input type="checkbox" checked={replace} onChange={event => setReplace(event.target.checked)}/>Replace the selection with the new block</label><p className="st-note" style={{ marginTop: 9 }}>Version 1 stores this sequence. Each scenario references that version and keeps its own input values.</p></div><div><h3 className="st-inspector-section-title">Expose parameters<span className="st-count">{parameters.length}</span></h3><p className="st-note" style={{ marginBottom: 13 }}>Choose the values that future uses can override. Everything else stays in the shared workflow.</p><div style={{ maxHeight: 405, overflow: 'auto' }}>{candidates.map(({ block, def, input }) => {
    const active = parameters.find(param => param.instanceId === block.id && param.input === input.key);
    return <div className="st-parameter-row" key={`${block.id}-${input.key}`}><label className="st-check-field"><input type="checkbox" data-testid={`expose-param-${block.id}-${input.key}`} checked={!!active} onChange={() => toggleParameter(block.id, input.key, input.label, input.type)}/><span>{input.label}<small style={{ display: 'block', fontSize: 9, color: '#a1b0a6', marginTop: 2 }}>{def.label} · {input.type}</small></span></label>{active && <div className="st-field-inline"><Field label="Parameter name"><input aria-label={`${input.label} parameter name`} value={active.key} onChange={event => setParameters(parameters.map(param => param === active ? { ...param, key: event.target.value } : param))}/></Field><Field label="Display label"><input aria-label={`${input.label} parameter label`} value={active.label} onChange={event => setParameters(parameters.map(param => param === active ? { ...param, label: event.target.value } : param))}/></Field></div>}</div>;
  })}{!candidates.length && <p className="st-note">The selected sequence has no simple values to expose. It can still be reused as a complete flow.</p>}</div></div></div></div><footer className="st-modal-footer"><span className="st-small">{selection.length} top-level blocks · {parameters.length} parameters</span><button type="button" className="st-button" onClick={onClose} disabled={busy}>Cancel</button><button className="st-button st-button-primary" disabled={busy || !name.trim() || !selection.length} data-testid="confirm-promote-workflow">{busy ? <LoaderCircle className="st-spin" size={13}/> : <Layers3 size={13}/>}Create reusable block</button></footer></form></Modal>;
}

export function HelpDialog({ onClose, onExample }: { onClose: () => void; onExample: (id: string) => void }) {
  return <Modal title="A business flow, one block at a time" subtitle="Folio turns a business case into a repeatable browser test. Try the standard draft first, then see how the Italy referral adds exceptions and new roles." onClose={onClose} wide><div className="st-modal-body"><div className="st-help-grid">{[
    ['Build a small flow', 'As Broker → Create standard policy → Expect Draft. This creates a customer and saves a real two-location policy in the insurance desk.'],
    ['Describe what changes', 'Put modifiers inside a location. Preview “Warehouse should be in Italy” and confirm the exact country and address change. Headquarters and issuing market remain German.'],
    ['Give the sequence a name', 'Save useful steps as one reusable block. Expose inputs such as flood limit. A variation overrides those inputs while its shared version stays pinned.'],
    ['Run and inspect the evidence', 'Run the exact saved flow through Chromium. Each business step links to its result, created object IDs, and a screenshot. The full run stays in history.'],
  ].map(([title, copy], index) => <div className="st-help-step" key={title}><span>{index + 1}</span><h3>{title}</h3><p>{copy}</p></div>)}</div><div className="st-help-example"><strong>The more demanding example</strong><br/>A German manufacturer, an Italian warehouse, and €1,000,000 flood coverage. The broker requests a quote. A senior underwriter reviews a risk survey and approves the referral. The broker issues the policy and checks its schedule.</div><p className="st-help-note">The product rules are fictional. Every operation and test runs locally. Free text uses a documented local vocabulary and a saved confirmation, so its meaning does not change on each run.</p></div><footer className="st-modal-footer"><button className="st-button" onClick={() => onExample('italy-referral')}><GitBranch size={13}/>Explore the Italy referral</button><button className="st-button st-button-primary" onClick={() => onExample('standard-draft')}><Play size={12}/>Start with a draft</button></footer></Modal>;
}

export function AddBlockDialog({ catalog, onClose, onAdd }: { catalog: StudioCatalog; onClose: () => void; onAdd: (definition: BlockDefinition) => void }) {
  const [query, setQuery] = useState('');
  const defs = newestDefinitions(catalog).filter(def => `${def.label} ${KIND_LABELS[def.kind]}`.toLowerCase().includes(query.toLowerCase()));
  return <Modal title="Add a business block" subtitle="Actions join the selected actor. Modifiers go into the selected location or draft configuration." onClose={onClose}><div className="st-modal-body"><label className="st-search"><Search size={14}/><input aria-label="Find block to add" placeholder="Search by a business action…" value={query} onChange={event => setQuery(event.target.value)} autoFocus/></label><div style={{ maxHeight: 450, overflow: 'auto' }}>{defs.map(def => <button className="st-palette-item" style={{ padding: '10px 8px', fontSize: 12 }} key={versionKey(def)} onClick={() => onAdd(def)} aria-label={`Insert ${def.label}`}><KindIcon kind={def.kind} contextType={def.contextType}/><span>{def.label}<small style={{ display: 'block', fontSize: 9, color: '#a5ada8', marginTop: 3 }}>{KIND_LABELS[def.kind]} · v{def.version}</small></span><Plus size={13} style={{ marginLeft: 'auto' }}/></button>)}</div></div></Modal>;
}
