import { ArrowRight, Check, CheckCheck, ChevronDown, ChevronRight, Circle, Clock3, Code2, Download, ExternalLink, FileCheck2, Image, Layers3, LoaderCircle, Play, ShieldCheck, X } from 'lucide-react';
import { useState } from 'react';
import type { RunRecord } from '../../shared/blocks';
import { EmptyState, formatDate, JsonView, Status } from './ui';

export function RunHistory({ runs, selectedId, onSelect, onStart, onNavigate }: {
  runs: RunRecord[]; selectedId?: string; onSelect: (id: string) => void; onStart: () => void; onNavigate: (section: string) => void;
}) {
  const [filter, setFilter] = useState('all');
  const filtered = runs.filter(run => filter === 'all' || run.status === filter);
  const selected = runs.find(run => run.id === selectedId) || filtered[0];
  return <div className="st-content"><div className="st-content-toolbar"><div className="st-filter-tabs" role="tablist" aria-label="Filter runs">{['all', 'passed', 'failed', 'running'].map(value => <button key={value} role="tab" aria-selected={filter === value} onClick={() => setFilter(value)}>{value === 'all' ? 'All runs' : value.charAt(0).toUpperCase() + value.slice(1)}{value === 'all' && <span className="st-count" style={{ marginLeft: 6 }}>{runs.length}</span>}</button>)}</div><span className="st-note">Local Chromium · evidence saved with every run</span></div>{runs.length ? <div className="st-runs-layout"><div className="st-run-list" aria-label="Run history">{filtered.map(run => <button className="st-run-item" key={run.id} aria-selected={selected?.id === run.id} onClick={() => onSelect(run.id)}><div className="st-run-item-top"><span className="st-small">{run.id.slice(-8)}</span><Status status={run.status}/></div><h3>{run.scenarioName}</h3><div className="st-run-item-footer"><span>{formatDate(run.startedAt)}</span><span>revision {run.scenarioRevision}</span></div></button>)}{!filtered.length && <EmptyState icon={<Clock3 size={20}/>} title="No matching runs">Choose another status to see its runs.</EmptyState>}</div>{selected && <RunDetail run={selected} onNavigate={onNavigate}/>}</div> : <div className="st-run-empty"><EmptyState icon={<Play size={21}/>} title="Your first run starts in the studio" action={<button className="st-button st-button-primary" onClick={onStart}><Play size={12}/>Open a scenario</button>}>Run a business flow through the insurance application. Its exact inputs, browser steps, screenshots, and resulting policy will appear here.</EmptyState></div>}</div>;
}

export function RunDrawer({ run, onClose, onHistory, onNavigate }: { run: RunRecord; onClose: () => void; onHistory: () => void; onNavigate: (section: string) => void }) {
  return <aside className="st-run-drawer" role="dialog" aria-modal="false" aria-label="Scenario run"><div className="st-run-drawer-top"><span><Play size={13} style={{ marginRight: 7 }}/>SCENARIO RUN</span><div className="st-inline-row"><button className="st-button st-button-quiet st-button-small" onClick={onHistory}>Run history<ArrowRight size={11}/></button><button className="st-icon-button" onClick={onClose} aria-label="Close run panel"><X size={16}/></button></div></div><RunDetail run={run} onNavigate={onNavigate}/></aside>;
}

export function RunDetail({ run, onNavigate }: { run: RunRecord; onNavigate: (section: string) => void }) {
  const [showSource, setShowSource] = useState(false);
  const [showManifest, setShowManifest] = useState(false);
  const [screenshot, setScreenshot] = useState<string>();
  const complete = run.events.filter(event => event.status === 'passed').length;
  const total = run.compiled.steps.length;
  const launchFailure = !!run.error && /browserType\.launch|executable|chromium|browser.*closed|failed to launch/i.test(run.error);
  const failureSummary = launchFailure ? 'The browser could not start this run.' : run.error?.split('\n')[0].slice(0, 240);
  const policyId = run.objectIds.issuedPolicy || run.objectIds.amendedPolicy || run.objectIds.policy || Object.entries(run.objectIds).find(([key]) => key.toLowerCase().includes('policy'))?.[1];
  return <article className="st-run-detail"><header className="st-run-detail-header"><div><h2>{run.scenarioName}</h2><p>Revision {run.scenarioRevision} · {formatDate(run.startedAt)} · {run.browser || 'Chromium'}</p></div><span data-testid="run-status"><Status status={run.status}/></span></header><div className="st-run-progress" aria-label={`${complete} of ${total} steps passed`}><div style={{ width: `${total ? complete / total * 100 : 0}%` }}/></div><div className="st-run-detail-body">
    <div className="st-run-summary"><div><small>STEPS PASSED</small><strong>{complete}<span style={{ color: '#b8c2ba', fontSize: 11 }}> / {total}</span></strong></div><div><small>DURATION</small><strong>{run.durationMs !== undefined ? `${(run.durationMs / 1000).toFixed(1)}s` : run.status === 'running' ? 'Running' : 'Queued'}</strong></div><div><small>SCENARIO</small><strong>v{run.scenarioRevision}<span style={{ color: '#b8c2ba', fontSize: 10 }}> pinned</span></strong></div></div>
    {policyId && <div className="st-run-policy"><FileCheck2 size={21} color="#83a58b"/><span><strong>{run.status === 'passed' ? 'Policy created by this run' : 'Policy in progress'}</strong><small>{policyId}</small></span><button className="st-button st-button-small" data-testid="open-run-policy" onClick={() => onNavigate(`/insurance/policies/${encodeURIComponent(policyId)}`)}>Open policy<ArrowRight size={11}/></button></div>}
    {run.error && <div className="st-alert st-alert-error" role="alert" style={{ margin: '0 0 17px' }}><Circle size={12}/><span>{failureSummary}<details style={{ marginTop: 7 }}><summary style={{ cursor: 'pointer', fontSize: 10 }}>Technical details</summary><pre className="st-source-pre" style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', maxHeight: 250 }}>{run.error}</pre></details></span></div>}
    <div className="st-inspector-section-title">Business steps<span className="st-small" style={{ fontWeight: 400 }}>Real browser execution</span></div>
    <div className="st-run-steps" data-testid="run-steps">{run.compiled.steps.map(step => {
      const event = run.events.find(item => item.id === step.id || item.instanceId === step.instanceId);
      return <div className={`st-run-step st-run-step-${event?.status || 'pending'}`} key={step.id} data-testid={`run-step-${step.instanceId}`}><span className="st-run-step-icon">{event?.status === 'passed' ? <Check size={12}/> : event?.status === 'failed' ? <X size={12}/> : event?.status === 'running' ? <LoaderCircle className="st-spin" size={12}/> : <Circle size={8}/>}</span><div className="st-run-step-copy"><h3>{step.label}</h3><p>{step.actor}{event?.error ? ` · ${event.error.split('\n')[0].slice(0, 180)}` : event?.objectIds && Object.keys(event.objectIds).length ? ` · ${Object.keys(event.objectIds).length} linked records` : event?.status === 'running' ? ' · interacting with the insurance desk' : ''}</p>{event?.screenshot && <div className="st-run-artifacts"><button className="st-button st-button-small" style={{ fontSize: 9, padding: '3px 6px' }} onClick={() => setScreenshot(event.screenshot)}><Image size={10}/>Screenshot</button></div>}{event?.error && <details style={{ marginTop: 7 }}><summary className="st-note" style={{ cursor: 'pointer' }}>Technical failure details</summary><pre className="st-source-pre" style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{event.error}</pre></details>}{(event?.details || event?.objectIds && Object.keys(event.objectIds).length > 0) && <details style={{ marginTop: 7 }}><summary className="st-note" style={{ cursor: 'pointer' }}>Evidence</summary><JsonView value={{ ...(event?.details || {}), objectIds: event?.objectIds }} label="Step evidence"/></details>}</div><span>{event?.durationMs !== undefined ? `${(event.durationMs / 1000).toFixed(1)}s` : event?.status === 'running' ? 'Live' : '—'}</span></div>;
    })}</div>
    <div className="st-test-source"><button onClick={() => setShowSource(!showSource)} aria-expanded={showSource} data-testid="show-generated-source"><span><Code2 size={13} style={{ marginRight: 7 }}/>Generated Playwright source</span>{showSource ? <ChevronDown size={13}/> : <ChevronRight size={13}/>}</button>{showSource && <pre className="st-source-pre" tabIndex={0}>{run.compiled.generatedSource}</pre>}</div>
    <div className="st-test-source" style={{ marginTop: 9 }}><button onClick={() => setShowManifest(!showManifest)} aria-expanded={showManifest}><span><Layers3 size={13} style={{ marginRight: 7 }}/>Exact run manifest and revisions</span>{showManifest ? <ChevronDown size={13}/> : <ChevronRight size={13}/>}</button>{showManifest && <JsonView value={{ id: run.id, error: run.error, scenarioRevision: run.scenarioRevision, fingerprint: run.compiled.fingerprint, catalogRevision: run.compiled.catalogRevision, implementationRevision: run.compiled.implementationRevision, blockVersions: run.compiled.blockVersions, templateVersions: run.compiled.templateVersions, resolutionIds: run.compiled.resolutionIds, objectIds: run.objectIds }} label="Run manifest"/>}</div>
    {(run.trace || run.video) && <div className="st-run-artifacts" style={{ marginTop: 15 }}>{run.trace && <a href={run.trace} download><Download size={11}/>Playwright trace</a>}{run.video && <a href={run.video} target="_blank" rel="noreferrer"><ExternalLink size={11}/>Browser recording</a>}</div>}
    <p className="st-note" style={{ marginTop: 18 }}>The compiled scenario pins every block, template, and confirmed interpretation. This run remains reviewable after the scenario changes.</p>
  </div>{screenshot && <div className="st-modal-overlay" onClick={() => setScreenshot(undefined)} role="dialog" aria-label="Run screenshot" aria-modal="true"><div style={{ maxWidth: 1100, maxHeight: '90vh', overflow: 'auto', background: '#fff', borderRadius: 10, padding: 10 }} onClick={event => event.stopPropagation()}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '5px 5px 12px', fontSize: 12 }}><span>Browser evidence</span><button className="st-icon-button" onClick={() => setScreenshot(undefined)} aria-label="Close screenshot"><X size={17}/></button></div><img src={screenshot} alt="Insurance application at this business step" style={{ display: 'block', width: '100%', maxWidth: 1050, height: 'auto', border: '1px solid #e7ece9', borderRadius: 5 }}/></div></div>}</article>;
}
