import test from 'node:test';
import assert from 'node:assert/strict';
import type { TestingBlockDefinition, TestingCatalog, TestingCompiledScenario } from '../../../shared/testing';
import { BUSINESS_SCHEMA, decodeBusinessDraft, decodeTechnicalPlan, DUPLICATES_SCHEMA, duplicateSchemaFor, REUSE_SCHEMA, reuseSchemaFor, TECHNICAL_SCHEMA, validateTestingCaseDesign } from './schemas';
import { validateDuplicateReview } from './reviews';
import { duplicateReviewContext } from './duplicate-context';
import { duplicatePrompt } from './prompts';

const definition = (id: string, version: string, origin: TestingBlockDefinition['origin'] = 'human'): TestingBlockDefinition => ({
  id, version, origin, name: 'Freigabeberechtigung prüfen', description: 'Prüft eine fachliche Berechtigung.', kind: 'assertion', category: 'Prüfungen',
  semanticKey: id, inputs: [{ key: 'expectedRole', label: 'Erwartete Rolle', type: 'text' }], outputs: [], knowledgeRefs: [], preconditions: [], postconditions: [], status: 'draft', createdAt: '2026-01-01',
});
const compiled = (...definitions: TestingBlockDefinition[]) => ({ definitions }) as TestingCompiledScenario;
const subject = definition('pruefung.sonderfreigabe', '1.0.0');
const comparison = definition('pruefung.bestehende-freigabe', '2.0.0', 'seed');
const catalog: TestingCatalog = { definitions: [subject, comparison], bindings: [], knowledge: [], revision: 'test' };
const decision = (proposed = { id: subject.id, version: subject.version }) => ({ proposed, decision: 'new', chosen: null as null | { id:string;version:string }, reason: 'Die Berechtigung ist eine eigene fachliche Prüfung.', compatible: false });
const branches = (schema:any):any[] => schema.anyOf ?? [schema];
// Evaluate only the JSON-schema vocabulary generated by this decision contract.
function accepts(schema:any,value:any):boolean {
  if(schema.anyOf)return schema.anyOf.some((branch:any)=>accepts(branch,value));
  if(schema.enum&&!schema.enum.includes(value))return false;
  if(schema.type==='null')return value===null;
  if(schema.type==='string')return typeof value==='string';
  if(schema.type==='boolean')return typeof value==='boolean';
  if(schema.type==='object')return !!value&&typeof value==='object'&&!Array.isArray(value)&&schema.required.every((key:string)=>Object.hasOwn(value,key))&&Object.keys(value).every(key=>Object.hasOwn(schema.properties,key)&&accepts(schema.properties[key],value[key]));
  return true;
}

test('Dynamisches Dublettenschema koppelt Prüfgegenstand und ausschließlich andere Vergleichspaare', () => {
  const schema = duplicateSchemaFor(compiled(subject),catalog), variants=branches(schema.properties.decisions.items);
  for(const variant of variants){assert.deepEqual(variant.properties.proposed.properties.id.enum,[subject.id]);assert.deepEqual(variant.properties.proposed.properties.version.enum,[subject.version]);assert.equal(variant.additionalProperties,false);}
  assert(accepts(schema.properties.decisions.items,decision()));
  assert(!accepts(schema.properties.decisions.items,{...decision(),decision:'reuse',chosen:decision().proposed,compatible:true}));
  assert(!accepts(schema.properties.decisions.items,{...decision(),decision:'extend',chosen:{id:'unbekannt',version:'1.0.0'}}));
  assert(accepts(schema.properties.decisions.items,{...decision(),decision:'reuse',chosen:{id:comparison.id,version:comparison.version},compatible:true}));
  for(const text of [schema.properties.explanation,...variants.map(item=>item.properties.reason),schema.properties.unresolved.items]){assert.equal(text.type,'string');assert.equal(text.enum,undefined);}
});

test('Mehrere Prüfgegenstände erlauben nur tatsächlich vorhandene ID-Versionspaare und schließen jeden Selbstvergleich aus', () => {
  const second=definition('pruefung.zweite-berechtigung','3.1.0'),c={...catalog,definitions:[...catalog.definitions,second]},scenario=compiled(subject,second);
  const schema=duplicateSchemaFor(scenario,c).properties.decisions.items;
  for(const item of [subject,second]) {
    const self={id:item.id,version:item.version};assert(!accepts(schema,{...decision(self),decision:'reuse',chosen:self}));
    assert(accepts(schema,decision(self)));
  }
  assert(!accepts(schema,decision({id:subject.id,version:second.version})));
  const context=JSON.parse(duplicateReviewContext(scenario,c)['vergleichskandidaten.json']);
  for(const row of context)assert(row.candidates.every((item:any)=>item.id!==row.proposed.id||item.version!==row.proposed.version));
  assert.equal(context[0].noMatch.decision,'new');assert.equal(context[0].noMatch.chosen,null);
});

test('Schema-Refinements verändern weder andere Aufrufe noch Basisschemas oder Wiederverwendungsfelder', () => {
  const original=JSON.stringify({duplicates:DUPLICATES_SCHEMA,reuse:REUSE_SCHEMA});
  const first=duplicateSchemaFor(compiled(subject),catalog);duplicateSchemaFor(compiled(comparison),catalog);
  assert.deepEqual(branches(first.properties.decisions.items)[0].properties.proposed.properties.id.enum,[subject.id]);
  const parameter=reuseSchemaFor(compiled(subject)).properties.suggestions.items.properties.parameters.items.properties;
  assert.deepEqual(parameter.input.enum,['expectedRole']);for(const key of ['key','instanceId','label'])assert.equal(parameter[key].enum,undefined);
  assert.equal(JSON.stringify({duplicates:DUPLICATES_SCHEMA,reuse:REUSE_SCHEMA}),original);
  assert.equal(duplicateSchemaFor(compiled(comparison),catalog).properties.decisions.maxItems,0);
});

test('Validator berichtet beide Selbstvergleiche gemeinsam und ändert keine fachliche Entscheidung stillschweigend', () => {
  const second=definition('pruefung.zweite-berechtigung','3.1.0'),c={...catalog,definitions:[...catalog.definitions,second]};
  const raw={explanation:'Synthetische Reproduktion zweier Selbstvergleiche.',decisions:[subject,second].map(item=>({...decision({id:item.id,version:item.version}),decision:'reuse',chosen:{id:item.id,version:item.version},compatible:true})),unresolved:[]};
  const before=JSON.stringify(raw);
  assert.throws(()=>validateDuplicateReview(raw,compiled(subject,second),c),error=>{const message=(error as Error).message;for(const text of ['2 Vertragsfehler','decisions[0]','decisions[1]',subject.id,second.id,'decision:"new", chosen:null'])assert(message.includes(text),message);return true;});
  assert.equal(JSON.stringify(raw),before);
  const valid={...raw,decisions:[{...raw.decisions[0],decision:'extend',chosen:{id:comparison.id,version:comparison.version},compatible:false},decision({id:second.id,version:second.version})]};
  assert.deepEqual(validateDuplicateReview(valid,compiled(subject,second),c),valid);
  assert.throws(()=>validateDuplicateReview({...raw,decisions:[decision({id:'1.0.0',version:'1.0.0'})]},compiled(subject,second),c),/Erlaubte Prüfgegenstände/);
});


test('Ein vorhandener Prüfgegenstand ohne andere Kandidaten bleibt eine eigenständige Entscheidung',()=>{
  const alone={...catalog,definitions:[subject]},scenario=compiled(subject),schema=duplicateSchemaFor(scenario,alone);
  assert(accepts(schema.properties.decisions.items,decision()));
  assert(!accepts(schema.properties.decisions.items,{...decision(),decision:'reuse',chosen:decision().proposed}));
  assert.deepEqual(validateDuplicateReview({explanation:'Keine andere Definition vorhanden.',decisions:[decision()],unresolved:[]},scenario,alone).decisions,[decision()]);
  assert.throws(()=>validateDuplicateReview({explanation:'',decisions:[],unresolved:[]},scenario,alone),/fehlt in der unabhängigen/);
  assert.match(duplicatePrompt(),/Ist pruefgegenstaende.json leer/);assert.match(duplicatePrompt(),/nur die Kandidatenliste.*dennoch eine Entscheidung new/);
});

test('Andere Versionen derselben Baustein-ID werden nicht als fachliche Dublette angeboten',()=>{
  const older={...subject,version:'0.9.0'},c={...catalog,definitions:[...catalog.definitions,older]},scenario=compiled(subject),schema=duplicateSchemaFor(scenario,c);
  const versionSwap={...decision(),decision:'reuse',chosen:{id:older.id,version:older.version},compatible:true};
  assert(!accepts(schema.properties.decisions.items,versionSwap));
  assert.throws(()=>validateDuplicateReview({explanation:'',decisions:[versionSwap],unresolved:[]},scenario,c),/andere Version desselben Bausteins, keine Dublette/);
  const context=JSON.parse(duplicateReviewContext(scenario,c)['vergleichskandidaten.json'])[0];
  assert.deepEqual(context.versions.map((item:any)=>item.version),['0.9.0']);assert(context.candidates.every((item:any)=>item.id!==subject.id));
});

test('Technische Lücken liefern genaue Revisionsdaten statt einer bloßen Meldung',()=>{
  const issue={kind:'business-contract',summary:'Ein deaktivierter Button löst keine HTTP-Antwort aus.',affectedDefinitionRefs:[{id:subject.id,version:subject.version}],affectedInputKeys:['expectedRole'],blockPaths:['berechtigung'],suggestedBusinessRevision:'Entferne die nicht beobachtbare HTTP-Status-Erwartung und behalte die Bedienbarkeitsprüfung bei.'};
  const decoded=decodeTechnicalPlan({explanation:'Nicht ausführbar.',reuseBindings:[],newBindings:[],unsupported:[issue]});
  assert.deepEqual(decoded.unsupported,[issue]);
  assert.equal(TECHNICAL_SCHEMA.properties.unsupported.items.properties.blockPaths.minItems,1);
  assert.throws(()=>decodeTechnicalPlan({explanation:'Zu ungenau.',reuseBindings:[],newBindings:[],unsupported:['HTTP fehlt']}));
});

test('Das Agentenschema erlaubt ausdrücklich Definitionseingaben ohne Standardwert', () => {
  const defaultSchema = BUSINESS_SCHEMA.properties.newDefinitions.items.properties.inputs.items.properties.defaultJson;
  assert(defaultSchema.anyOf.some((branch: any) => branch.type === 'null'));
  const draft = decodeBusinessDraft({
    title: 'Rollenwahl', expectedOutcome: 'Die gewählte Rolle ist sichtbar.', blocks: [], knowledgeRefs: [], explanation: '', assumptions: [], openQuestions: [], matrix: null,
    newDefinitions: [{ id: 'fixture.rolle', version: '1.0.0', name: 'Als Rolle', description: '', kind: 'context', category: 'Ablauf', semanticKey: 'execution.actor',
      inputs: [{ key: 'role', label: 'Rolle', type: 'choice', required: true, defaultJson: null, description: '', options: [{ value: 'Sachbearbeiter', label: 'Sachbearbeiter' }], fieldsJson: '[]', minimum: null, maximum: null, extensible: false }],
      outputs: [], knowledgeRefs: [], preconditions: [], postconditions: [], operation: null, bindingId: null, body: [], exports: [] }], newKnowledge: [],
  });
  assert.equal(draft.newDefinitions[0].inputs[0].default, undefined);
});

test('Fallplanung unterscheidet lineare Rollenwechsel von Varianten und erhält widersprüchliche Sollwerte zur Klärung',()=>{
  assert.match(duplicatePrompt(),/pruefgegenstaende\.json/);
  const draft:any={caseDesign:{mode:'matrix',dimensions:['Rolle'],expectedCaseCount:2,expectedResults:['Freigabe','Ablehnung'],rationale:'Zwei Rollen.'},matrix:{
    columns:[{id:'rolle',label:'Rolle',target:{blockPath:'kontext',inputPath:'role'},role:'input',type:'choice'},{id:'ergebnis',label:'Ergebnis',target:{blockPath:'pruefung',inputPath:'expected'},role:'expectation',type:'text'}],
    rows:[{id:'eins',label:'Sachbearbeitung',enabled:true,values:{rolle:'Sachbearbeitung',ergebnis:'Freigabe'}},{id:'zwei',label:'Direktion',enabled:true,values:{rolle:'Sachbearbeitung',ergebnis:'Ablehnung'}}],
  }};
  const errors=validateTestingCaseDesign(draft);
  assert.equal(errors.length,1);assert.match(errors[0],/CASE_DESIGN_CONFLICTING_EXPECTATIONS/);assert.match(errors[0],/Sachbearbeitung.*Direktion/);assert.match(errors[0],/entferne keine Erwartung stillschweigend/);
});
