import { useEffect, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import type { TestingAgentSettings } from '../../shared/testing';
import { messageOf, testingApi } from './api';
import { Notice, Spinner } from './ui';

const argsText = (args: string[]) => args.map(value => /^[\w./:=+-]+$/.test(value) ? value : JSON.stringify(value)).join(' ');
export function AgentSettings({ onSaved }: { onSaved: (settings: TestingAgentSettings) => void }) {
  const [settings, setSettings] = useState<TestingAgentSettings>();
  const [argumentsByKey, setArguments] = useState<Record<string, string>>({});
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  function loaded(value: TestingAgentSettings) { setSettings(value); setArguments(Object.fromEntries([...Object.entries(value.providers).map(([id, provider]) => [`provider:${id}`, argsText(provider.extraArgs)]), ...value.models.map(model => [`model:${model.id}`, argsText(model.extraArgs)])])); }
  async function reload(signal?: AbortSignal) { try { loaded(await testingApi<TestingAgentSettings>('/settings', { signal })); setError(''); } catch (cause) { if (!signal?.aborted) setError(messageOf(cause)); } }
  useEffect(() => { const controller = new AbortController(); void reload(controller.signal); return () => controller.abort(); }, []);
  async function save() {
    if (!settings || busy) return; setBusy(true); setError(''); setNotice('');
    try {
      const payload = { ...settings, providers: Object.fromEntries(Object.entries(settings.providers).map(([id, provider]) => [id, { ...provider, extraArgs: argumentsByKey[`provider:${id}`] ?? '' }])), models: settings.models.map(model => ({ ...model, extraArgs: argumentsByKey[`model:${model.id}`] ?? '' })) };
      const saved = await testingApi<TestingAgentSettings>('/settings', { method: 'PUT', body: JSON.stringify(payload) });
      loaded(saved); onSaved(saved); setNotice('Einstellungen gespeichert. Neue KI-Aufträge verwenden diese Konfiguration.');
    } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); }
  }
  if (!settings) return <div className="t-page"><h1>Einstellungen</h1>{error ? <><Notice tone="error">{error}</Notice><button className="t-button" onClick={() => void reload()}>Erneut laden</button></> : <Spinner label="Einstellungen werden geladen" />}</div>;
  return <div className="t-page t-settings-page"><header className="t-page-heading"><div><span className="t-eyebrow">LOKALE KI-AUSFÜHRUNG</span><h1>Einstellungen</h1><p>Konfiguriere Codex und Claude Code sowie die Modelle für deine KI-Aufträge.</p></div></header>{error && <Notice tone="error">{error}</Notice>}{notice && <Notice tone="success">{notice}</Notice>}<form onSubmit={event => { event.preventDefault(); void save(); }}><fieldset disabled={busy} style={{ border: 0, padding: 0, margin: 0 }}>
    <section className="t-settings-section"><h2>Modelle</h2><p className="t-settings-help">Jedes Modell hat einen Anzeigenamen, einen Provider und den Modellnamen der jeweiligen CLI. Diese Modelle stehen in allen KI-Aufträgen zur Auswahl.</p>{settings.models.map((model, index) => <div className="t-settings-model" key={model.id}><label className="t-field">Anzeigename<input aria-label={`Anzeigename Modell ${index + 1}`} required value={model.label} onChange={event => setSettings({ ...settings, models: settings.models.map(item => item.id === model.id ? { ...item, label: event.target.value } : item) })} /></label><label className="t-field">Modellname / Slug<input aria-label={`Modellname Modell ${index + 1}`} required value={model.slug} placeholder="z. B. sonnet" onChange={event => setSettings({ ...settings, models: settings.models.map(item => item.id === model.id ? { ...item, slug: event.target.value } : item) })} /></label><button type="button" className="t-icon" aria-label={`Modell ${model.label || index + 1} entfernen`} disabled={settings.models.length < 2} onClick={() => { const models = settings.models.filter(item => item.id !== model.id); setSettings({ ...settings, models, defaultModel: settings.defaultModel === model.id ? models[0].id : settings.defaultModel }); }}><Trash2 size={16} /></button><label className="t-field">Provider<select aria-label={`Provider Modell ${index + 1}`} value={model.provider} onChange={event => setSettings({ ...settings, models: settings.models.map(item => item.id === model.id ? { ...item, provider: event.target.value as 'codex' | 'claude' } : item) })}><option value="codex">Codex</option><option value="claude">Claude Code</option></select></label><label className="t-field">Zusätzliche Modellargumente<input aria-label={`Zusätzliche Argumente Modell ${index + 1}`} value={argumentsByKey[`model:${model.id}`] ?? ''} placeholder={model.provider === 'claude' ? '--effort high' : '-c model_reasoning_effort=high'} onChange={event => setArguments({ ...argumentsByKey, [`model:${model.id}`]: event.target.value })} /></label></div>)}<button type="button" className="t-button small" onClick={() => setSettings({ ...settings, models: [...settings.models, { id: `modell-${crypto.randomUUID()}`, label: '', provider: 'codex', slug: '', extraArgs: [] }] })}><Plus size={14} />Modell hinzufügen</button><label className="t-field" style={{ marginTop: 20 }}>Standardmodell<select aria-label="Standardmodell" value={settings.defaultModel} onChange={event => setSettings({ ...settings, defaultModel: event.target.value })}>{settings.models.map(model => <option key={model.id} value={model.id}>{model.label || 'Neues Modell'} · {model.provider === 'claude' ? 'Claude Code' : 'Codex'}</option>)}</select></label></section>
    {(['codex', 'claude'] as const).map(id => <section className="t-settings-section" key={id}><h2>{id === 'codex' ? 'Codex' : 'Claude Code'}</h2><label className="t-field">CLI-Programm<input aria-label={`${id === 'codex' ? 'Codex' : 'Claude Code'} CLI-Programm`} placeholder={id === 'codex' ? 'codex' : 'claude'} value={settings.providers[id].executable} onChange={event => setSettings({ ...settings, providers: { ...settings.providers, [id]: { ...settings.providers[id], executable: event.target.value } } })} /></label><label className="t-field">Zusätzliche Providerargumente<input aria-label={`${id === 'codex' ? 'Codex' : 'Claude Code'} zusätzliche Argumente`} placeholder={id === 'claude' ? '--effort high' : '-c model_reasoning_effort=high'} value={argumentsByKey[`provider:${id}`] ?? ''} onChange={event => setArguments({ ...argumentsByKey, [`provider:${id}`]: event.target.value })} /></label><p className="t-settings-help">Ein leeres Programmfeld verwendet die lokale Standardkonfiguration. Argumente gelten für alle Modelle dieses Providers; Modellargumente kommen dazu. Werte mit Leerzeichen in Anführungszeichen setzen. Modellargumente überschreiben gleiche Providerargumente. Die Anmeldung erfolgt über die lokal installierte CLI.</p><p className="t-settings-help">{id === 'claude' ? 'Erlaubt: --effort low|medium|high|xhigh|max und --max-budget-usd mit positivem Betrag.' : 'Erlaubt: -c model_reasoning_effort=high und -c model_verbosity=low|medium|high. Nicht unterstützte Argumente werden beim Speichern erklärt.'}</p></section>)}
    <div className="t-dialog-actions"><button type="button" className="t-button" onClick={() => { void reload(); setNotice(''); }}>Änderungen verwerfen und neu laden</button><button type="submit" className="t-button primary">{busy ? 'Wird gespeichert …' : 'Einstellungen speichern'}</button></div></fieldset></form></div>;
}
