import type { TestingAgentJob } from '../../shared/testing';
import { JsonView, Notice } from './ui';
export function AgentFailure({ job }: { job: TestingAgentJob }) {
  if (!job.error && !job.termination) return null;
  const cause = job.termination?.cause;
  const timeLimit = cause === 'time_limit';
  const userCancelled = cause === 'user_cancelled';
  const interrupted = cause === 'parent_cancelled' || cause === 'interrupted' || !cause && job.status === 'failed' && /vom Menschen abgebrochen/i.test(job.error ?? '');
  const limit = job.termination?.limitMs ? job.termination.limitMs < 60_000 ? `${Math.round(job.termination.limitMs / 1000)} Sekunden` : `${Math.round(job.termination.limitMs / 60_000)} Minuten` : 'die vorgesehene Bearbeitungszeit';
  const duplicate = job.phase === 'duplicates' || /^(?:Dublettenprüfung:|Die unabhängige Dublettenprüfung ist fehlgeschlagen:)/.test(job.error ?? '');
  const login = /not logged in|please run \/login|authentication|unauthorized|nicht angemeldet/i.test(job.error ?? '');
  const startup = /ENOENT|executable|nicht gefunden|could not start|spawn/i.test(job.error ?? '');
  const title = timeLimit ? 'Die Bearbeitungszeit ist abgelaufen.' : userCancelled ? 'Du hast diesen Auftrag abgebrochen.' : cause === 'server_restart' ? 'Die Anwendung wurde während der Bearbeitung neu gestartet.' : cause === 'action_limit' ? 'Die Erkundung hat ihre Aktionsgrenze erreicht.' : cause === 'no_progress' ? 'Die Erkundung findet keine neuen Erkenntnisse.' : interrupted ? 'Die Bearbeitung wurde unterbrochen.' : login ? 'Die gewählte KI ist noch nicht angemeldet.' : startup ? 'Die gewählte KI konnte nicht gestartet werden.' : duplicate ? 'Der Vergleich mit vorhandenen Bausteinen konnte nicht abgeschlossen werden.' : job.phase === 'business' ? 'Der fachliche Entwurf konnte nicht abgeschlossen werden.' : job.phase === 'exploration' ? 'Die Erkundung konnte nicht abgeschlossen werden.' : job.phase === 'reuse' ? 'Die Wiederverwendungsanalyse konnte nicht abgeschlossen werden.' : 'Die technische Prüfung konnte nicht abgeschlossen werden.';
  return <section className="t-agent-failure" aria-label="Auftrag konnte nicht abgeschlossen werden"><Notice tone={userCancelled ? undefined : "error"}><strong>{title}</strong><p>{duplicate ? 'Die KI hat keinen gültigen Vergleich geliefert. Dieses Ergebnis wurde nicht übernommen. ' : ''}Dein gespeicherter fachlicher Ablauf bleibt erhalten.</p></Notice><p>{timeLimit ? `Für diesen Auftrag waren ${limit} vorgesehen. Sieh dir die bisherigen Beobachtungen an und starte die Erkundung erneut. Der bisherige Fachstand bleibt erhalten.` : interrupted ? 'Der Auftrag konnte nicht zu Ende bearbeitet werden. Es liegt keine bestätigte Abbruchaktion von dir vor. Starte ihn über die nächste Aktion erneut.' : cause === 'action_limit' || cause === 'no_progress' ? 'Sieh dir die bisherigen Beobachtungen an. Ergänze fehlende Angaben und starte die Erkundung erneut.' : login ? 'Melde dich in der CLI des gewählten Anbieters an. Prüfe unter Einstellungen, welcher Anbieter und welches Modell verwendet werden.' : startup ? 'Prüfe unter Einstellungen den Anbieter und den Pfad seiner CLI. Danach kannst du den Auftrag erneut starten.' : 'Prüfe die Hinweise und nutze die nächste Aktion in diesem Testfall, um fortzusetzen.'}</p><JsonView value={job.error} label="Technische Fehlerdetails anzeigen"/></section>;
}
