import { useState } from 'react';
import { Plus, Trash2, X, BookOpen } from 'lucide-react';
import type { TestingKnowledgeDocument } from '../../shared/testing';
import { Modal } from './ui';
export function DefinitionKnowledge({ documents, selected, newDocuments, onSelected, onNew }: { documents: TestingKnowledgeDocument[]; selected: string[]; newDocuments: TestingKnowledgeDocument[]; onSelected: (ids: string[]) => void; onNew: (documents: TestingKnowledgeDocument[]) => void }) {
  const [open, setOpen] = useState(false), [query, setQuery] = useState('');
  const [inspected, setInspected] = useState<TestingKnowledgeDocument>();
  const found = documents.filter(doc => `${doc.title} ${doc.summary}`.toLocaleLowerCase('de').includes(query.trim().toLocaleLowerCase('de')));
  function add() { const doc: TestingKnowledgeDocument = { id: `wissen.${crypto.randomUUID()}`, revision: 1, title: '', summary: '', content: '', kind: 'rule', origin: 'human', definitionRefs: [], relatedKnowledge: [], requiredFields: [], preconditions: [], postconditions: [] }; onNew([...newDocuments, doc]); onSelected([...selected, doc.id]); setOpen(false); }
  function change(index: number, patch: Partial<TestingKnowledgeDocument>) { onNew(newDocuments.map((doc, i) => i === index ? { ...doc, ...patch } : doc)); }
  return <section className="t-definition-knowledge" aria-label="Fachwissen zum Block">
    <div className="t-section-heading"><div><h3>Was muss der Agent über diesen Block wissen?</h3><p className="t-caption">Verknüpfe mindestens eine Wissensquelle oder beschreibe neues Wissen.</p></div><button className="t-button small" onClick={() => { setInspected(undefined); setOpen(true); }}><Plus size={14}/>Wissen hinzufügen</button></div>
    {!!selected.length && <div className="t-definition-knowledge-selection">{documents.filter(doc => selected.includes(doc.id)).map(doc => <span key={doc.id}><button onClick={() => { setInspected(doc); setOpen(true); }}><BookOpen size={13}/>{doc.title}</button><button aria-label={`Wissensquelle ${doc.title} entfernen`} onClick={() => onSelected(selected.filter(id => id !== doc.id))}><X size={13}/></button></span>)}</div>}
    {open && <Modal title={inspected ? inspected.title : 'Wissen hinzufügen'} subtitle={inspected ? 'Verknüpfte Wissensquelle' : 'Suche vorhandenes Wissen oder lege eine neue Quelle an.'} onClose={() => setOpen(false)} wide>
      {inspected ? <div className="t-definition-knowledge-search"><p>{inspected.summary}</p><p style={{whiteSpace:'pre-wrap'}}>{inspected.content}</p><button className="t-button" onClick={() => setInspected(undefined)}>Zur Wissensauswahl</button></div> : <div className="t-definition-knowledge-search"><label className="t-field">Vorhandenes Wissen suchen<input type="search" aria-label="Vorhandenes Wissen suchen" value={query} onChange={event => setQuery(event.target.value)} placeholder="Titel oder Thema suchen"/></label><div className="t-knowledge-choices">{found.map(doc => <label key={doc.id}><input type="checkbox" checked={selected.includes(doc.id)} onChange={event => onSelected(event.target.checked ? [...selected, doc.id] : selected.filter(id => id !== doc.id))}/><span>{doc.title}</span></label>)}{!found.length && <p>Kein passendes Wissen gefunden. Du kannst eine neue Quelle hinzufügen.</p>}</div><div className="t-dialog-actions"><button className="t-button" onClick={add}><Plus size={14}/>Neue Wissensquelle hinzufügen</button><button className="t-button primary" onClick={() => setOpen(false)}>Auswahl übernehmen</button></div></div>}
    </Modal>}
    {newDocuments.map((doc, index) => <fieldset className="t-new-knowledge" key={doc.id}><legend>Neue Wissensquelle {index + 1}</legend><div className="t-field"><label htmlFor={`knowledge-title-${index}`}>Titel des Wissens</label><input id={`knowledge-title-${index}`} value={doc.title} onChange={event => change(index, { title: event.target.value })} placeholder="Zum Beispiel: Regeln für tierärztliche Nachweise"/></div><div className="t-field"><label htmlFor={`knowledge-content-${index}`}>Fachliche Beschreibung</label><textarea id={`knowledge-content-${index}`} rows={4} value={doc.content} onChange={event => change(index, { content: event.target.value, summary: event.target.value.trim().split('\n')[0].slice(0, 240) })} placeholder="Welche Voraussetzungen, Eingaben und Ergebnisse gelten?"/></div><button className="t-button small" onClick={() => { onNew(newDocuments.filter((_, i) => i !== index)); onSelected(selected.filter(id => id !== doc.id)); }}><Trash2 size={13}/>Dieses Wissen entfernen</button></fieldset>)}
  </section>;
}
