import { useState } from 'react';
import { ArrowRight, Plus, Search } from 'lucide-react';
import type { TestingAgentJob, TestingRun, TestingScenario, TestingScenarioLifecycle } from '../../shared/testing';
import { Empty, formatDate } from './ui';
import { DetailsButton } from './DetailsButton';
import { phaseLabels, statusLabels } from './model';
const phaseNames = { request: 'Anforderung', exploration: 'Erkundung & Entwurf', review: 'Fachlich prüfen', technical: 'Technik & Prüfen', result: 'Ergebnis' };
export function ScenarioOverview({ scenarios, lifecycles = [], jobs, localDraft, onOpen, onCreate, onJob }: { scenarios: TestingScenario[]; lifecycles?: TestingScenarioLifecycle[]; runs: TestingRun[]; jobs: TestingAgentJob[]; localDraft: (scenario: TestingScenario) => TestingScenario; onOpen: (id: string) => void; onCreate: () => void; onJob: (job: TestingAgentJob) => void }) {
  const [query, setQuery] = useState('');
  const visible = scenarios.map(saved => ({ saved, current: localDraft(saved) })).filter(({ current }) => `${current.title} ${current.intent} ${current.naming?.summary ?? ''} ${current.naming?.tags.join(' ') ?? ''}`.toLocaleLowerCase('de').includes(query.trim().toLocaleLowerCase('de')));
  return <div className="t-page t-scenario-overview"><header className="t-page-heading"><div><span className="t-eyebrow">DEINE TESTFÄLLE</span><h1>Alle Testfälle</h1><p>Jeder gestartete Test bleibt hier. Setze genau dort fort, wo du aufgehört hast.</p></div><button className="t-button primary" onClick={onCreate}><Plus size={16}/>Testfall erstellen</button></header><section aria-label="Gespeicherte Testfälle"><label className="t-overview-search"><Search size={16}/><input type="search" aria-label="Testfälle durchsuchen" value={query} onChange={event => setQuery(event.target.value)} placeholder="Testfälle durchsuchen"/><span>{visible.length} Testfälle</span></label><div className="t-test-rows">{visible.map(({ saved, current }) => {
    const lifecycle = lifecycles.find(item => item.scenarioId === saved.id);
    const dirty = JSON.stringify(saved) !== JSON.stringify(current);
    const state = dirty ? 'Änderungen nicht gespeichert' : lifecycle?.status === 'running' ? 'In Bearbeitung' : lifecycle?.status === 'failed' ? 'Benötigt Aufmerksamkeit' : lifecycle?.runStatus === 'passed' ? 'Bestanden' : lifecycle?.status === 'attention' ? 'Deine Entscheidung' : !current.blocks.length ? 'Entwurf' : phaseNames[lifecycle?.phase ?? 'review'];
    return <button className="t-saved-test t-test-row" key={saved.id} data-scenario-revision={saved.revision} onClick={() => onOpen(saved.id)}><span className={`t-workspace-state-dot ${!dirty && lifecycle?.runStatus === 'passed' ? 'passed' : lifecycle?.status ?? 'idle'}`}/><span className="t-test-title"><strong>{current.title}</strong><small>{current.naming?.summary ?? current.intent}</small></span><span className="t-test-phase"><strong>{state}</strong><small>{dirty ? 'Fachlich prüfen' : phaseNames[lifecycle?.phase ?? 'review']}</small></span><span className="t-test-updated">{formatDate(saved.updatedAt)}</span><ArrowRight size={16}/></button>;
  })}</div>{!visible.length && <Empty title={scenarios.length ? 'Keine passenden Testfälle' : 'Dein erster Test beginnt mit einer Anforderung'} action={<button className="t-button" onClick={scenarios.length ? () => setQuery('') : onCreate}>{scenarios.length ? 'Suche zurücksetzen' : 'Testfall erstellen'}</button>}/>}</section>{jobs.length > 0 && <div className="t-overview-history"><DetailsButton label="Frühere KI-Aufträge ansehen"><section className="t-job-history" aria-label="Bisherige Agentenaufträge">{jobs.map(job => <button key={job.id} onClick={() => onJob(job)}><strong>{scenarios.find(item => item.id === job.scenarioId)?.title ?? 'Auftrag ohne Testfall'}</strong><span>{phaseLabels[job.phase]} · {statusLabels[job.status]} · {formatDate(job.startedAt)}</span><ArrowRight size={14}/></button>)}</section></DetailsButton></div>}</div>;
}
