import type { ReactNode } from 'react';
import type { TestingRun } from '../../shared/testing';
import { CheckCircle2, AlertCircle, LoaderCircle } from 'lucide-react';
import { JsonView, Notice } from './ui';
export function WorkspaceRunResult({ run, children }: { run: TestingRun; children?: ReactNode }) {
  const passed = run.status === 'passed';
  const failed = run.status === 'failed';
  const failedStep = run.steps.find(step => step.status === 'failed');
  return <section className={`t-workspace-result ${passed ? 'passed' : failed ? 'failed' : 'running'}`} aria-label="Prüfergebnis"><header>{passed ? <CheckCircle2 size={25}/> : failed ? <AlertCircle size={25}/> : <LoaderCircle className="t-spin" size={25}/>}<div><h2>{passed ? 'Der Test ist bestanden' : run.status === 'failed' ? 'Der Test hat eine Abweichung gefunden' : 'Die Prüfung läuft'}</h2><p>{run.steps.filter(step => step.status === 'passed').length} von {run.steps.length} Schritten bestanden · Revision {run.scenarioRevision}</p></div></header>{failed && <Notice tone="error">{failedStep ? `Die Prüfung ist bei „${failedStep.label}“ stehen geblieben. Öffne den Schrittnachweis, um die Ursache zu prüfen.` : 'Die Prüfung konnte nicht abgeschlossen werden. Öffne die technischen Details.'}</Notice>}{run.error && <JsonView value={run.error} label="Technische Fehlerdetails anzeigen"/>}<details open={!passed}><summary>Geprüfte Schritte und Nachweise</summary>{run.steps.map((step, index) => <details className="t-result-step" key={step.id}><summary><span>{index + 1}</span><strong>{step.label}</strong><small>{step.status === 'passed' ? 'Bestanden' : step.status === 'failed' ? 'Abweichung' : 'Noch offen'}</small></summary>{step.error && <JsonView value={step.error} label="Fehlerdetails dieses Schritts anzeigen"/>}{step.screenshot && <a href={step.screenshot} target="_blank" rel="noreferrer"><img src={step.screenshot} alt={`Nachweis: ${step.label}`}/></a>}<JsonView value={step} label="Technischen Schrittnachweis anzeigen"/></details>)}</details><details><summary>Wiederverwendung und Laufdetails</summary>{children}<JsonView value={run.compiled} label="Geprüften Fachstand anzeigen"/>{run.artifacts?.trace && <a href={run.artifacts.trace} download>Browser-Trace herunterladen</a>}</details></section>;
}
export function InlineReview({ title, subtitle, onClose, children }: { title: string; subtitle?: string; onClose: () => void; wide?: boolean; children?: ReactNode }) { return <section className="t-inline-review" aria-label={title}><header><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button className="t-button small" onClick={onClose}>Später prüfen</button></header>{children}</section>; }
