import type { ReactNode } from 'react';
import type { TestingRun } from '../../shared/testing';
import { CheckCircle2, AlertCircle, LoaderCircle } from 'lucide-react';
import { JsonView, Notice } from './ui';
export function WorkspaceRunResult({ run, children }: { run: TestingRun; children?: ReactNode }) {
  const passed = run.status === 'passed';
  const failed = run.status === 'failed';
  const failedStep = run.steps.find(step => step.status === 'failed');
  const matrix = run.mode === 'matrix' && !!run.matrixRows?.length;
  const count = matrix ? `${run.summary?.passed ?? 0} von ${run.summary?.total ?? run.matrixRows!.length} Testfällen bestanden${run.summary?.failed ? ` · ${run.summary.failed} mit Abweichung` : ''}` : `${run.steps.filter(step => step.status === 'passed').length} von ${run.steps.length} Schritten bestanden`;
  const matrixFailure = run.summary?.skipped ? `Mindestens ein Testfall weicht ab. ${run.summary.skipped} Testfälle wurden nicht ausgeführt.` : 'Mindestens ein Testfall weicht vom erwarteten Ergebnis ab. Die übrigen Testfälle wurden trotzdem ausgeführt.';
  return <section className={`t-workspace-result ${passed ? 'passed' : failed ? 'failed' : 'running'}`} aria-label="Prüfergebnis"><header>{passed ? <CheckCircle2 size={25}/> : failed ? <AlertCircle size={25}/> : <LoaderCircle className="t-spin" size={25}/>}<div><h2>{passed ? matrix ? 'Alle Testfälle sind bestanden' : 'Der Test ist bestanden' : run.status === 'failed' ? matrix ? 'Die Testmatrix hat Abweichungen gefunden' : 'Der Test hat eine Abweichung gefunden' : 'Die Prüfung läuft'}</h2><p>{count} · Revision {run.scenarioRevision}</p></div></header>{failed && <Notice tone="error">{matrix ? matrixFailure : failedStep ? `Die Prüfung ist bei „${failedStep.label}“ stehen geblieben. Öffne den Schrittnachweis, um die Ursache zu prüfen.` : 'Die Prüfung konnte nicht abgeschlossen werden. Öffne die technischen Details.'}</Notice>}{run.error && <JsonView value={run.error} label="Technische Fehlerdetails anzeigen"/>}{matrix ? <MatrixResults run={run}/> : <details open={!passed}><summary>Geprüfte Schritte und Nachweise</summary>{run.steps.map((step, index) => <details className="t-result-step" key={step.id}><summary><span>{index + 1}</span><strong>{step.label}</strong><small>{step.status === 'passed' ? 'Bestanden' : step.status === 'failed' ? 'Abweichung' : 'Noch offen'}</small></summary>{step.error && <JsonView value={step.error} label="Fehlerdetails dieses Schritts anzeigen"/>}{step.screenshot && <a href={step.screenshot} target="_blank" rel="noreferrer"><img src={step.screenshot} alt={`Nachweis: ${step.label}`}/></a>}<JsonView value={step} label="Technischen Schrittnachweis anzeigen"/></details>)}</details>}<details><summary>Wiederverwendung und Laufdetails</summary>{children}<JsonView value={run.compiled} label="Geprüften Fachstand anzeigen"/>{run.artifacts?.trace && <a href={run.artifacts.trace} download>Browser-Trace herunterladen</a>}</details></section>;
}
function MatrixResults({run}:{run:TestingRun}) { const columns=run.compiled.scenario.matrix?.columns??[]; const status=(value:string)=>value==='passed'?'Bestanden':value==='failed'?'Abweichung':value==='skipped'?'Nicht ausgeführt':value==='running'?'In Bearbeitung':'Noch offen'; return <div className="t-matrix-results" aria-label="Ergebnisse der Testmatrix">{run.matrixRows!.map(row=>{const failed=row.steps?.find(step=>step.status==='failed');return <details className={`t-matrix-result ${row.status}`} key={row.rowId} open={row.status==='failed'}><summary><span>{row.index+1}</span><strong>{row.rowLabel}</strong><small>{status(row.status)}</small></summary><div><dl>{Object.entries(row.values).map(([key,value])=><div key={key}><dt>{columns.find(column=>column.id===key)?.label??key}</dt><dd>{typeof value==='object'?JSON.stringify(value):String(value)}</dd></div>)}</dl>{failed&&<Notice tone="error">Der Prüfschritt „{failed.label}“ hat die erwartete Anzeige nicht bestätigt.</Notice>}{row.error&&<JsonView value={row.error} label={`Technische Fehlerdetails für ${row.rowLabel} anzeigen`}/>}<div className="t-run-steps">{row.steps?.map((step,index)=><details className="t-result-step" key={step.id}><summary><span>{index+1}</span><strong>{step.label}</strong><small>{status(step.status)}</small></summary>{step.error&&<JsonView value={step.error} label="Technische Fehlerdetails dieses Schritts anzeigen"/>}{step.screenshot&&<a href={step.screenshot} target="_blank" rel="noreferrer"><img src={step.screenshot} alt={`Nachweis: ${step.label}`}/></a>}</details>)}</div></div></details>;})}</div>; }
export function InlineReview({ title, subtitle, onClose, children }: { title: string; subtitle?: string; onClose: () => void; wide?: boolean; children?: ReactNode }) { return <section className="t-inline-review" aria-label={title}><header><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button className="t-button small" onClick={onClose}>Später prüfen</button></header>{children}</section>; }
