import { randomUUID } from 'node:crypto';
import { test, expect, type Page } from '@playwright/test';
import type { BlockDefinition, PromotionResult, Scenario } from '../shared/blocks';
import { api } from './helpers/api';

async function save(page: Page): Promise<Scenario> {
  const id = await page.getByTestId('scenario-select').inputValue();
  const pending = page.waitForResponse(response => response.request().method() === 'PUT' && new URL(response.url()).pathname === `/api/studio/scenarios/${id}`);
  await page.getByTestId('save-scenario').click();
  const response = await pending;
  expect(response.ok()).toBe(true);
  await expect(page.getByTestId('save-status')).toHaveText('All changes saved');
  return response.json();
}

async function clone(page: Page, seed: string, name: string): Promise<Scenario> {
  await page.goto('/studio');
  await page.getByTestId('scenario-select').selectOption(seed);
  await page.getByTestId('clone-scenario').click();
  await page.getByRole('textbox', { name: 'Scenario name', exact: true }).fill(`${name} ${randomUUID().slice(0, 8)}`);
  const pending = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === `/api/studio/scenarios/${seed}/duplicate`);
  await page.getByTestId('create-scenario-confirm').click();
  const response = await pending;
  expect(response.ok()).toBe(true);
  const scenario = await response.json() as Scenario;
  await expect(page.getByTestId('scenario-select')).toHaveValue(scenario.id);
  return scenario;
}

test('a newcomer reviews a text change, reloads the saved interpretation, and opens real run and storage evidence', async ({ page, request }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error' && !/Failed to load resource.*status of (403|409|422)/.test(message.text())) errors.push(message.text()); });
  const scenario = await clone(page, 'italy-referral', 'QA browser Italy');
  await page.getByTestId('block-warehouse-country-text').getByRole('button', { name: 'Select Describe a change', exact: true }).click();
  await page.getByRole('textbox', { name: 'Change request', exact: true }).fill('Increase the coverage');
  await page.getByTestId('interpret-modifier').click();
  await expect(page.getByRole('heading', { name: 'More detail needed', exact: true })).toBeVisible();
  await expect(page.getByTestId('run-scenario')).toBeDisabled();
  await page.getByRole('textbox', { name: 'Change request', exact: true }).fill('Warehouse should be in Italy');
  await page.getByTestId('interpret-modifier').click();
  await expect(page.getByTestId('interpretation-preview')).toContainText('Warehouse country');
  await expect(page.getByTestId('interpretation-preview')).toContainText('Customer headquarters');
  await expect(page.getByTestId('interpretation-preview')).toContainText('Policy issuing market');
  await page.getByTestId('confirm-interpretation').click();
  await expect(page.getByTestId('save-status')).toHaveText('All changes saved');
  await expect(page.getByTestId('interpretation-preview')).toContainText('Confirmed interpretation');
  const saved = await api<Scenario>(request, 'GET', `/api/studio/scenarios/${scenario.id}`);
  expect(saved.revision).toBeGreaterThan(scenario.revision);
  await page.reload();
  await expect(page.getByTestId('scenario-select')).toHaveValue(scenario.id);
  await page.getByTestId('block-warehouse-country-text').getByRole('button', { name: 'Select Describe a change', exact: true }).click();
  await expect(page.getByRole('textbox', { name: 'Change request', exact: true })).toHaveValue('Warehouse should be in Italy');
  await expect(page.getByTestId('interpretation-preview')).toContainText('Confirmed interpretation');
  await page.screenshot({ path: testInfo.outputPath('studio-reviewed-change-desktop.png'), fullPage: true });

  await page.getByTestId('run-scenario').click();
  await expect(page.getByTestId('run-status')).toHaveText('passed', { timeout: 90_000 });
  await expect(page.getByTestId('run-step-approval').getByRole('heading', { name: 'Approve referral', exact: true })).toBeVisible();
  await page.getByTestId('show-generated-source').click();
  await expect(page.locator('.st-source-pre')).toContainText('executeCompiledStep');
  await page.getByRole('button', { name: 'Screenshot', exact: true }).first().click();
  await expect(page.getByRole('dialog', { name: 'Run screenshot', exact: true }).getByRole('img', { name: 'Insurance application at this business step', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Close screenshot', exact: true }).click();
  await page.getByRole('button', { name: 'Close run panel', exact: true }).click();
  await page.getByTestId('inspect-storage').click();
  await page.getByTestId('explore-storage-graph').click();
  const graph = page.getByRole('dialog', { name: 'How the records connect', exact: true });
  await graph.getByRole('combobox', { name: 'Storage record kind', exact: true }).selectOption('implementation');
  await graph.locator('[data-testid^="graph-node-"]').first().click();
  await expect(graph.getByRole('heading', { name: 'Connected records', exact: true })).toBeVisible();
  await expect(graph.locator('pre')).toContainText('supportedDefinitions');
  await page.screenshot({ path: testInfo.outputPath('studio-storage-graph.png'), fullPage: true });
  await page.keyboard.press('Escape');
  await expect(graph).not.toBeVisible();
  expect(errors).toEqual([]);
});

test('the browser editor adds, changes, reorders and deletes blocks, then promotes and reuses a parameterized version', async ({ page, request }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error' && !/Failed to load resource.*status of (403|409|422)/.test(message.text())) errors.push(message.text()); });
  const first = await clone(page, 'standard-draft', 'QA reusable draft');
  const actor = page.getByTestId('block-standard-broker').getByRole('button', { name: 'Select As Broker', exact: true });
  await actor.focus();
  await page.keyboard.press('Enter');
  await page.getByRole('combobox', { name: 'Role', exact: true }).selectOption('Senior underwriter');
  await expect(page.getByTestId('validation-issues')).toContainText('Broker');
  await page.getByRole('combobox', { name: 'Role', exact: true }).selectOption('Broker');
  await page.getByTestId('block-standard-check').getByRole('button', { name: 'Select Expect policy state', exact: true }).click();
  await page.getByTestId('add-block-property.request-quote').click();
  await page.getByRole('combobox', { name: 'Policy', exact: true }).selectOption('policy');
  const quoteId = await page.locator('.st-block-selected').getAttribute('data-block-id');
  expect(quoteId).toBeTruthy();
  await page.getByTestId(`block-${quoteId}`).getByRole('button', { name: 'Move Request quote up', exact: true }).click();
  const reordered = await save(page);
  expect(reordered.blocks[0].children![1].definition.id).toBe('property.request-quote');
  await page.getByTestId(`block-${quoteId}`).getByRole('button', { name: 'Delete Request quote', exact: true }).click();
  const deleted = await save(page);
  expect(deleted.blocks[0].children).toHaveLength(2);

  await page.getByTestId('block-standard-create').getByRole('button', { name: 'Select Create standard policy', exact: true }).click();
  await page.getByTestId('add-block-context.location').click();
  await page.getByRole('combobox', { name: 'Location', exact: true }).selectOption('Warehouse');
  await page.getByTestId('add-block-location.add-flood').click();
  await page.getByRole('spinbutton', { name: 'Flood limit', exact: true }).fill('500000');
  const floodId = await page.locator('.st-block-selected').getAttribute('data-block-id');
  const withFlood = await save(page);
  expect(withFlood.blocks[0].children![0].changes![0].changes![0].inputs.limit).toBe(500_000);
  await page.getByTestId('promote-workflow').click();
  const workflowName = `QA reusable property draft ${randomUUID().slice(0, 8)}`;
  await page.getByRole('textbox', { name: 'Reusable block name', exact: true }).fill(workflowName);
  await page.getByTestId(`expose-param-${floodId}-limit`).check();
  await page.getByRole('textbox', { name: 'Flood limit parameter name', exact: true }).fill('floodLimit');
  const promotionResponse = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/studio/promote');
  await page.getByTestId('confirm-promote-workflow').click();
  const promotion = await (await promotionResponse).json() as PromotionResult;
  expect(promotion.definition.kind).toBe('workflow');
  await expect(page.getByRole('spinbutton', { name: 'Flood limit', exact: true })).toHaveValue('500000');

  await page.getByTestId('new-scenario').click();
  await page.getByRole('textbox', { name: 'Scenario name', exact: true }).fill(`QA second reusable draft ${randomUUID().slice(0, 8)}`);
  await page.getByRole('combobox', { name: 'Scenario starting point', exact: true }).selectOption('empty');
  const createdResponse = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/studio/scenarios');
  await page.getByTestId('create-scenario-confirm').click();
  const second = await (await createdResponse).json() as Scenario;
  await page.getByTestId(`add-block-${promotion.definition.id}`).click();
  await page.getByRole('spinbutton', { name: 'Flood limit', exact: true }).fill('650000');
  const reused = await save(page);
  expect(reused.blocks[0].definition).toEqual({ id: promotion.definition.id, version: 1 });
  expect(reused.blocks[0].inputs.floodLimit).toBe(650_000);
  await page.getByTestId('run-scenario').click();
  await expect(page.getByTestId('run-status')).toHaveText('passed', { timeout: 90_000 });
  await page.getByRole('button', { name: 'Close run panel', exact: true }).click();

  await page.getByRole('link', { name: 'Block library', exact: true }).click();
  await page.getByTestId(`inspect-definition-${promotion.definition.id}`).click();
  await page.getByTestId('edit-block-version').click();
  await page.getByRole('textbox', { name: 'Version description', exact: true }).fill('A new version with a different default limit');
  await page.getByRole('spinbutton', { name: 'Flood limit', exact: true }).fill('400000');
  const versionResponse = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname.endsWith('/versions'));
  await page.getByTestId('publish-block-version').click();
  const version = await (await versionResponse).json() as { definition: BlockDefinition };
  expect(version.definition.version).toBe(2);
  const pinnedFirst = await api<Scenario>(request, 'GET', `/api/studio/scenarios/${first.id}`);
  const pinnedSecond = await api<Scenario>(request, 'GET', `/api/studio/scenarios/${second.id}`);
  expect(pinnedFirst.blocks[0].definition.version).toBe(1);
  expect(pinnedFirst.blocks[0].inputs.floodLimit).toBe(500_000);
  expect(pinnedSecond.blocks[0].definition.version).toBe(1);
  expect(pinnedSecond.blocks[0].inputs.floodLimit).toBe(650_000);
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  await page.getByRole('link', { name: 'Scenario studio', exact: true }).click();
  await expect(page.getByTestId('scenario-select')).toHaveValue(second.id);
  await expect(page.getByTestId('upgrade-block-version')).toBeVisible();
  await page.setViewportSize({ width: 900, height: 1000 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('studio-reusable-small.png'), fullPage: true });
  expect(errors).toEqual([]);
});
